import { Poppins } from 'next/font/google';
import "./globals.css";
import StoreProvider from './StoreProvider'
import Background from './components/Background'

const poppins = Poppins({
  weight: ['400', '600', '700'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${poppins.className} w-full flex relative`}>
        <StoreProvider>
          <Background/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
