import localFont from "next/font/local";
import { Poppins } from 'next/font/google';
import "./globals.css";
import StoreProvider from './StoreProvider'
import Background from './components/Background'

const poppins = Poppins({
  weight: ['400', '600', '700'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} w-full flex relative`}>
        <StoreProvider>
          <Background/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
